name: release

on:
  workflow_dispatch: {}
env:
  APP_NAME: 'justfile'
  RUST_VERSION: '1.60.0'
  MAINTAINER: ''
  DESC: 'Just do it'
jobs:
  build-artifact:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Prepare debpkg dist
        run: |
          mkdir -p deb/debpkg/usr/bin
          cp -p target/x86_64-unknown-linux-gnu/release/just deb/debpkg/usr/bin/
          cp -p deb/just/* deb/debpkg
      - uses: jiro4989/build-deb-action@v3
        with:
          package: ${{ env.APP_NAME }}
          package_root: deb/
          maintainer: ${{ env.MAINTAINER }}
          version: ${{ github.ref }}
          arch: 'amd64'
          desc: '${{ env.DESC }}'

      - uses: jiro4989/build-rpm-action@v2
        with:
          summary: '${{ env.DESC }}'
          package: ${{ env.APP_NAME }}
          package_root: .rpmpkg
          maintainer: ${{ env.MAINTAINER }}
          version: ${{ github.ref }}
          arch: 'x86_64'
          desc: '${{ env.DESC }}'

      - uses: actions/upload-artifact@v3
        with:
          name: artifact-deb
          path: |
            ./*deb/debpkg